FROM php:5.6-fpm

MAINTAINER Paul Allen <paul@paulallen.org>

ADD ./edufocal.ini /usr/local/etc/php/conf.d
ADD ./vh-edufocal.pool.conf /usr/local/etc/php-fpm.d/


RUN apt-get update && apt-get install -y \
  libpq-dev \
  libmemcached-dev \
  curl \
  mysql-client \
  git \
  rsync \
  gnupg \
  openssh-server \
  libpng-dev \
  libfreetype6-dev \
  libcurl4-openssl-dev \
  libssl-dev \
  libmcrypt-dev \
  --no-install-recommends && \
  rm -r /var/lib/apt/lists/*


# configure gd library
RUN docker-php-ext-configure gd \
  --enable-gd-native-ttf \
  --with-freetype-dir=/usr/include/freetype2

# Install extensions using the helper script provided by the base image
RUN docker-php-ext-install \
  pdo_mysql \
  mysqli \
  curl \
  gd \
  mcrypt

# Install xdebug

#  echo 'xdebug.remote_host=192.168.1.45' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
#  echo 'xdebug.remote_connect_back=1' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
RUN pecl install xdebug-2.5.5 && \
  docker-php-ext-enable xdebug
RUN echo 'xdebug.remote_enable=1' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
  echo 'xdebug.remote_port=9001' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
  echo 'xdebug.remote_host=192.168.1.135' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
  echo 'xdebug.remote_handler=dbgp' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
  echo 'xdebug.profiler_enable=0' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
  echo 'xdebug.var_display_max_depth=-1' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
  echo 'xdebug.var_display_max_children=-1' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
  echo 'xdebug.var_display_max_data=-1' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
  echo 'xdebug.idekey="PHPSTORM"' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
  echo 'xdebug.remote_autostart=1' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
  echo 'xdebug.remote_log=/var/log/xdebug.log' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
  echo 'xdebug.profiler_output=/var/www/edufocal' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
  sed -i.old '1s;^;[xdebug]\n;' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

ADD ./php.ini-development /usr/local/etc/php/php.ini

# PHP www-user UID and GID
# ARG PUID="1000"
# ARG PGID="1000"


# add a php www-user instead of nobody
# RUN addgroup --gid ${PGID} www-user && \
  # adduser  --no-create-home --uid ${PUID}  www-user 
  # && \
  # sed -i "s|^user = .*|user = www-user|g" /etc/php7/php-fpm.d/www.conf && \
  # sed -i "s|^group = .*|group = www-user|g" /etc/php7/php-fpm.d/www.conf


# composer
RUN curl --silent --show-error --fail --location \
  --header "Accept: application/tar+gzip, application/x-gzip, application/octet-stream" \
  "https://getcomposer.org/installer" \
  | php -- --install-dir=/usr/bin --filename=composer

#nodejs
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install nodejs -y


WORKDIR /var/www/edufocal

CMD ["php-fpm"]

EXPOSE 9000
