version: '2'

services:

  php:
    build:
      context: ./php
      dockerfile: Dockerfile-70
    volumes_from:
      - application
      - api
    expose:
      - "9000"
    links:
      - mysql
      - workspace

  application:
    build: ./application
    volumes:
      - ../webapp:/var/www/edufocal

  api:
    build: ./api
    volumes:
      - ../api:/var/www/api

  messages:
    build: ./messages
    volumes:
      - ../messages:/var/www/messages
      - ../messages/node_modules:/var/www/messages/node_modules
    tty: true
    expose:
      - "3000"

  data:
    build: ./data
    volumes:
      - /var/docker/edufocal/mysql:/var/lib/mysql
      - /data

  nginx:
    build: ./nginx
    volumes_from:
      - application
      - api
    volumes:
      - ./logs/nginx/:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
      - messages
      - workspace
    networks:
      default:
        aliases:
          - apione

  mysql:
    build: ./mysql
    volumes_from:
      - data
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: edufocal_prod
      MYSQL_USER: efuser 
      MYSQL_PASSWORD: 12desciples
      MYSQL_ROOT_PASSWORD: root

  redis:
    build: ./redis
    volumes_from:
      - data
    ports:
      - "6378:6379"

  workspace:
    build: ./workspace
    volumes_from:
      - application
      - api
      - messages
    expose:
      - "8000"
    tty: true
