version: '3'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile-56
    env_file:
      - config.env

    volumes:
      - ./helper.sh:/var/www/edufocal/helper.sh
      - ./api:/var/www/edufocal/api
      - ./webapp:/var/www/edufocal/webapp
      - ~/.ssh:/root/.ssh
    links:
      - mysql
      - redis

  redis:
    image: redis:latest
    ports:
      - "6378:6379"

  mysql:
    image: mysql:5.6
    volumes:
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - config.env
    # environment:
    #   - MYSQL_DATABASE:${DB_DATABASE}
    #   - MYSQL_USER:${DB_USERNAME}
    #   - MYSQL_PASSWORD:${DB_PASSWORD}
    #   - MYSQL_ROOT_PASSWORD:${DB_PASSWORD}

  nginx:
    image:  nginx:1.7
    volumes:
      - ./data/logs/:/var/log/nginx
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/webapp.conf:/etc/nginx/sites-available/webapp.conf
      - ./docker/nginx/api.conf:/etc/nginx/sites-available/api.conf
      - ./docker/nginx/scribe.conf:/etc/nginx/sites-available/scribe.conf
    ports:
      - "80:80"
      - "443:443"
    links:
      - php

  # caddy:
  #   image: abiosoft/caddy:php
  #   ports:
  #     - "9000:80"
  #   volumes:
  #     - ./Caddyfile:/etc/Caddyfile
  #     - .:/srv
  #   env_file:
  #     - config.env

  
